// lemma-bench: loads a lemma-is .bin file, runs lemmatize calls, and reports
// process memory (mach task_info) so the mmap strategy can be verified.
//
// Usage:
//   swift run -c release lemma-bench <path-to-bin-morph.core.bin> [iterations]
//   swift run -c release lemma-bench <path-to-bin-morph.core.bin> --verify <fixture.json>
//
// The --verify mode checks lemmatize() output against a JSON fixture
// ({ word: [lemmas] }) generated by the TypeScript implementation.

import Foundation
import LemmaCore

struct MemorySample {
    let residentBytes: UInt64
    let physFootprintBytes: UInt64

    static func current() -> MemorySample {
        #if !canImport(Darwin)
            // Mach task_info is Apple-only; a Linux host builds the harness
            // and reports no footprint rather than not building at all.
            return MemorySample(residentBytes: 0, physFootprintBytes: 0)
        #else
            var info = task_vm_info_data_t()
            var count = mach_msg_type_number_t(
                MemoryLayout<task_vm_info_data_t>.size / MemoryLayout<integer_t>.size)
            let kr = withUnsafeMutablePointer(to: &info) {
                $0.withMemoryRebound(to: integer_t.self, capacity: Int(count)) {
                    task_info(mach_task_self_, task_flavor_t(TASK_VM_INFO), $0, &count)
                }
            }
            guard kr == KERN_SUCCESS else {
                return MemorySample(residentBytes: 0, physFootprintBytes: 0)
            }
            // phys_footprint is what the iOS jetsam memory limit is enforced on.
            return MemorySample(
                residentBytes: info.resident_size, physFootprintBytes: UInt64(info.phys_footprint))
        #endif
    }
}

func mb(_ bytes: UInt64) -> String {
    String(format: "%.2f MB", Double(bytes) / 1024 / 1024)
}

let args = CommandLine.arguments
guard args.count >= 2 else {
    print("usage: lemma-bench <path-to-bin-morph.core.bin> [iterations]")
    exit(1)
}
let binPath = args[1]

if args.count >= 4, args[2] == "--verify" {
    let lemmatizer = try BinaryLemmatizer(contentsOf: URL(fileURLWithPath: binPath))
    let fixture = try JSONDecoder().decode(
        [String: [String]].self, from: Data(contentsOf: URL(fileURLWithPath: args[3])))
    var mismatches = 0
    for (word, expected) in fixture {
        let got = lemmatizer.lemmatize(word)
        if got != expected {
            mismatches += 1
            print("MISMATCH \(word): expected \(expected), got \(got)")
        }
    }
    print("verified \(fixture.count) words, \(mismatches) mismatches")
    exit(mismatches == 0 ? 0 : 1)
}

let iterations = args.count >= 3 ? Int(args[2]) ?? 1000 : 1000

let words = [
    "börnin", "keypti", "hestinum", "manninum", "konunni", "húsið", "bókina",
    "skólanum", "fjöllin", "morguninn", "fórum", "gengum", "borðaði", "skrifaði",
    "stærri", "bestur", "góðan", "fallegasta", "við", "þeirra", "eftir", "án",
    "bílastæði", "flugvöllur", "tölvupóstur", "æðislegur", "öðruvísi", "ánægður",
    "xyzzyunknown", "javascript",
]

let before = MemorySample.current()
print("before load:      resident=\(mb(before.residentBytes))  footprint=\(mb(before.physFootprintBytes))")

let t0 = Date()
let lemmatizer = try BinaryLemmatizer(contentsOf: URL(fileURLWithPath: binPath))
let loadMs = Date().timeIntervalSince(t0) * 1000

let afterLoad = MemorySample.current()
print("after mmap load:  resident=\(mb(afterLoad.residentBytes))  footprint=\(mb(afterLoad.physFootprintBytes))  (load \(String(format: "%.2f", loadMs)) ms)")
print("file: \(mb(UInt64(lemmatizer.bufferSize)))  version=\(lemmatizer.version)  words=\(lemmatizer.wordFormCount)  lemmas=\(lemmatizer.lemmaCount)  bigrams=\(lemmatizer.bigramCount)")

let t1 = Date()
var totalLemmas = 0
for i in 0..<iterations {
    totalLemmas += lemmatizer.lemmatize(words[i % words.count]).count
}
let lookupMs = Date().timeIntervalSince(t1) * 1000

let afterCalls = MemorySample.current()
print("after \(iterations) calls: resident=\(mb(afterCalls.residentBytes))  footprint=\(mb(afterCalls.physFootprintBytes))  (\(String(format: "%.1f", lookupMs)) ms total, \(String(format: "%.1f", lookupMs / Double(iterations) * 1000)) µs/call, \(totalLemmas) lemmas)")

print("delta from start: resident=+\(mb(afterCalls.residentBytes - min(afterCalls.residentBytes, before.residentBytes)))  footprint=+\(mb(afterCalls.physFootprintBytes - min(afterCalls.physFootprintBytes, before.physFootprintBytes)))")
